// import React, { useState, useEffect } from 'react'
import appwriteService from '../appwrite/config'
import { Container, PostCard } from '../components'

function AllPosts() {
    // const [posts, setPosts] = useState([])   // State to store the list of posts fetched from the backend

    // useEffect runs when the component mounts (because of [])
    useEffect(() => {
        appwriteService.getPosts([])   // getPosts takes an array of filters/queries. Here [] means "no filters" -> fetch ALL posts
            .then((posts) => {
                if (posts) {
                    // Example API response: { total: 5, documents: [ { $id: 'abc', title: 'Post1' }, ... ] }
                    setPosts(posts.documents)   // posts.documents -> 'documents' is where Appwrite stores the actual list of posts
                }
            })
            .catch((error) => console.error('Failed to fetch posts:', error))
    }, [])   // Empty dependency array -> runs only once on mount

    return (
        <div className='w-full py-8'>
            {/* Container centers content and applies consistent width & padding */}
            <Container>
                <div className='flex flex-wrap'>   {/* flex flex-wrap -> makes posts wrap into rows */}
                    {posts?.map((post) => (
                        <div key={post.$id} className='p-2 w-1/4'>   {/* $id is auto-generated by Appwrite for each document */}
                            <PostCard {...post} />   {/* Spread operator ...post: Takes every property of the post object and passes it as a separate prop to PostCard */}
                        </div>
                    ))}
                </div>
            </Container>
        </div>
    )
}

export default AllPosts